### ISSUE TITLE
Missmatched versions betweeb tags/Gem versions

### ISSUE THREAD

**Issue by multani** [sensu-plugins/sensu-plugins-consul#13]
0.0.8 as been tagged in April, but it is not available as a Gem on https://rubygems.org/gems/sensu-plugins-consul/

Latest version available there is 0.1.7, which is not present as a tag on Git

**Comment by eheydrick** [comment]
OK somehow the CHANGELOG, tags, and actual release got out of whack. We'll sort it out. Thanks for letting us know.

**Comment by eheydrick** [comment]
I tagged [0.1.7 ](https://github.com/sensu-plugins/sensu-plugins-consul/releases/tag/0.1.7) at the commit that was released to rubygems and updated the CHANGELOG to have the correct version.
