### ISSUE TITLE
Checking all services with check-consul-service-health.rb not working

### ISSUE THREAD

**Issue by teemutm** [sensu-plugins/sensu-plugins-consul#14]
/opt/sensu/embedded/bin/check-consul-service-health.rb -a
Check failed to run: wrong number of arguments (given 0, expected 1), ["/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/diplomat-0.14.0/lib/diplomat/health.rb:20:in `checks'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/diplomat-0.14.0/lib/diplomat/rest_client.rb:46:in `method_missing'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-consul-0.1.7/bin/check-consul-service-health.rb:54:in `acquire_service_data'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-consul-0.1.7/bin/check-consul-service-health.rb:67:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]

**Comment by wg-tsuereth** [comment]
The Diplomat library wasn't being used correctly for `--all`.  This is fixed in PR #16, although it can be quite slow (one HTTP round-trip for the services list, and then another for each service healthcheck).

**Comment by eheydrick** [comment]
PR #16 is in 1.0.0, which is now on rubygems.
