### ISSUE TITLE
Release latest changes

### ISSUE THREAD

**Issue by andrewbunday** [sensu-plugins/sensu-plugins-consul#23]
Hi, 

I was wondering if we might be able to get the current unreleased master pushed out as a new version? 

Thanks, 
Andrew

**Comment by eheydrick** [comment]
Yes! Working on a new release.

**Comment by eheydrick** [comment]
1.2.0 is live on rubygems.

**Comment by andrewbunday** [comment]
Thanks for this. Much appreciated.
